<?php

namespace App\Models;



use App\Observers\Tenant\TenantObserver;
use App\Scopes\Tenant\TenantScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Webpatser\Uuid\Uuid;


class Promotion extends Model
{

    protected $fillable = ['description','start_date','end_date','img','promotion_value','tenant_id','uui','url','slug'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::addGlobalScope(new TenantScope);
        static::observe(new TenantObserver);

        self::creating(function($model){
            $model->uuid = (string) Uuid::generate(4);
            $model->slug = (string) Str::slug($model->description,'_');
            $model->url = (string) self::gerarUrl($model->description);
        });
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public static function gerarUrl($string){

        $baseUrl = env('APP_URL').'/promo/';

        $slug = Str::slug($string,'_');

        $url = $baseUrl.$slug;

        return $url;
    }

}
