<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Scopes\User\UserScope;

class Promocao extends Model
{
    protected $fillable = ['descricao','valor_promocional','data_inicio','data_final','foto','user_id'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new UserScope());
    }
}
