<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Webpatser\Uuid\Uuid;

class Tenant extends Model
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            $model->uuid = (string) Uuid::generate(4);
        });
    }


    protected $fillable = ['name','uuid'];

    public function users(){
        return $this->hasMany(User::class);
    }
}
